### ISSUE TITLE
Column headers are transformed to lower case during table upload

### ISSUE THREAD

**Issue by mtstahl** [pekrau/DbShare#384]
When uploading a CSV file to create a new table, the column headers are transformed to lower case.

Example:
Column header `S_1` becomes `s_1` after the upload.

Expected behaviour: No changes applied.

**Comment by pekrau** [comment]
The problem here is that Sqlite3 is insensitive to character case, so to reduce potential confusionI decided to lowercase all column names. Maybe that is a bad idea. Hmm. Will have to consider.

**Comment by mtstahl** [comment]
It could be a bug source when using the column headers of one table as key in another. However, one could also circumvent this by not using this strategy.

**Comment by mtstahl** [comment]
Also: when inserting new rows from file, I get a column mismatch error because of the lower case transformation.

**Comment by pekrau** [comment]
OK, will fix this.
